import java.util.ListResourceBundle;

public class Resources_tr extends ListResourceBundle {

    private static final Object[][] contents = {
            {MessageType.DISCONNECTION.name(), "Sunucu kullanılamaz"},
            {MessageType.COMMAND_UNDONE.name(), "Komut başarısız oldu"},
            {MessageType.MAX_NUMBER.name(), "Maksimum kullanıcı sayısı"},
            {MessageType.FALSE_LOGIN.name(), "Yanlış giriş veya şifre"},
            {MessageType.FALSE_REGISTER_LOGIN.name(), "Yanlış giriş biçimi"},
            {MessageType.ALREADY_EXIST.name(), "Bu ada sahip bir kullanıcı zaten var"},
            {MessageType.TRUE_REGISTER_LOGIN.name(), "E-posta benzersiz bir kod gönderdi"},
            {MessageType.TOKEN_IS_ACTIVE.name(), "Böyle bir kullanıcı zaten var ya da bu kullanıcı için bir simge hala aktif"},
            {MessageType.TRUE_REGISTRATION.name(), "Sen kayıtlı"},
            {MessageType.FALSE_REGISTRATION.name(), "Benzersiz kod yanlış"},
            {MessageType.ERROR.name(), "Veri alma hatası"},
            {MessageType.TOKEN_UNREACHED.name(), "Belirteç süresi doldu"},
            {MessageType.JSON_EXCEPTION.name(), "Dosya ayrıştırma hatası"},
            {TextType.UNKNOWN_MESSAGE.name(), "Sunucudan bilinmeyen mesaj"},
            {TextType.WRITE_TOKEN.name(), "Belirteci girin"},
            {TextType.MESSAGE_SENDED.name(), "Soruşturma gönderildi"},
            {TextType.WRONG_FORMAT_TOKEN.name(), "Yanlış simge biçimi"},
            {TextType.WRONG_FORMAT_PORT.name(), "Yanlış port formatı"},
            {TextType.MAX_PORT_SIZE.name(), "Eşik aşıldı"},
            {TextType.CHECK_BUTTON.name(), "Bağlan"},
            {TextType.EXIT_BUTTON.name(), "Çıkış"},
            {TextType.PORT_LABEL.name(), "Bağlantıyı gir"},
            {TextType.RUSSIAN.name(), "Rus"},
            {TextType.TURKISH.name(), "Türk"},
            {TextType.UKRAINIAN.name(), "Ukrayna"},
            {TextType.SPANISH_NI.name(), "İspanyol"},
            {TextType.WRITE_LOGIN.name(), "Giriş girin"},
            {TextType.WRITE_PASSWORD.name(), "Şifreyi girin"},
            {TextType.LOGIN_BUTTON.name(), "Giriş"},
            {TextType.REGISTER_BUTTON.name(), "Kayıt"},
            {TextType.BACK_BUTTON.name(), "Geri"},
            {TextType.LOGIN_LABEL.name(), "Giriş"},
            {TextType.PASSWORD_LABEL.name(), "şifre"},
            {TextType.CHOOSE_OBJECT.name(), "Bir nesne seçin"},
            {TextType.CHOOSE_PATH.name(), "Yolu belirtin"},
            {TextType.TABLE.name(), "Tablo"},
            {TextType.PANEL.name(), "Grafik resim"},
            {TextType.WELCOME_LABEL.name(), "Hoşgeldiniz, "},
            {TextType.CHANGER_LABEL.name(), "Editör"},
            {TextType.DATE_LABEL.name(), "Tesis tarihi:"},
            {TextType.SIZE_LABEL.name(), "Boyut:"},
            {TextType.NAME_LABEL.name(), "Ad:"},
            {TextType.CUP_OF_TEA.name(), "Bir fincan çay"},
            {TextType.FULLNESS_LABEL.name(), "Tamlık:"},
            {TextType.TEA_TYPE_LABEL.name(), "Çay türü:"},
            {TextType.ADD_BUTTON.name(), "Eklemek"},
            {TextType.CHANGE_BUTTON.name(), "Değiştirmek"},
            {TextType.REMOVE_BUTTON.name(), "Kaldırmak"},
            {TextType.REMOVE_ALL_BUTTON.name(), "Tümünü sil"},
            {TextType.REMOVE_GREATER_BUTTON.name(), "Büyük kaldırmak"},
            {TextType.IMPORT_BUTTON.name(), "Dosyadan İçe Aktar"},
            {TextType.CLASS_COLLECTION_LABEL.name(), "Koleksiyon türü nesneleri depolar: Alice"},
            {TextType.PATH_LABEL.name(), "Yol:"},
            {TextType.COLLECTION_LABEL.name(), "Koleksiyon"},
            {TextType.COUNT_LABEL.name(), "Koleksiyondaki nesne sayısı:"},
            {TextType.FILE_NOT_EXIST.name(), "Dosya yok"},
            {TextType.IS_NOT_FILE.name(), "Bu bir dosya değil"},
            {TextType.CANNOT_READ.name(), "Dosya okunamıyor"},
            {TextType.OWNER_LABEL.name(), "Sahip:"},
            {TextType.POLITENESS_LABEL.name(), "Nezaket:"},
    };

    @Override
    protected Object[][] getContents() {
        return contents;
    }
}
