import java.util.ListResourceBundle;

public class Resources_uk extends ListResourceBundle {

    private static final Object[][] contents = {
            {MessageType.DISCONNECTION.name(), "Сервер недоступний"},
            {MessageType.COMMAND_UNDONE.name(), "Команда не виконана"},
            {MessageType.MAX_NUMBER.name(), "Максимальне число користувачів"},
            {MessageType.FALSE_LOGIN.name(), "Неправильний логін або пароль"},
            {MessageType.FALSE_REGISTER_LOGIN.name(), "Неправильний формат логіна"},
            {MessageType.ALREADY_EXIST.name(), "Користувач з таким ім'ям вже існує"},
            {MessageType.TRUE_REGISTER_LOGIN.name(), "Вам на пошту відправлений унікальний код"},
            {MessageType.TOKEN_IS_ACTIVE.name(), "Такий користувач вже існує, або токен для цього користувача ще активний"},
            {MessageType.TRUE_REGISTRATION.name(), "Ви зареєстровані"},
            {MessageType.FALSE_REGISTRATION.name(), "Неправильно вказано унікальний код"},
            {MessageType.ERROR.name(), "Помилка отримання даних"},
            {MessageType.TOKEN_UNREACHED.name(), "Час токена минув"},
            {MessageType.JSON_EXCEPTION.name(), "Помилка парсинга файлу"},
            {TextType.UNKNOWN_MESSAGE.name(), "Невідоме повідомлення від сервера"},
            {TextType.WRITE_TOKEN.name(), "Введіть токен"},
            {TextType.MESSAGE_SENDED.name(), "Запит відправлений"},
            {TextType.WRONG_FORMAT_TOKEN.name(), "Неправильний формат токена"},
            {TextType.WRONG_FORMAT_PORT.name(), "Неправильний формат порту"},
            {TextType.MAX_PORT_SIZE.name(), "Перевищено поріг"},
            {TextType.CHECK_BUTTON.name(), "Підключатися"},
            {TextType.EXIT_BUTTON.name(), "Вихід"},
            {TextType.PORT_LABEL.name(), "Введіть порт"},
            {TextType.RUSSIAN.name(), "Руський"},
            {TextType.TURKISH.name(), "Турецький"},
            {TextType.UKRAINIAN.name(), "Український"},
            {TextType.SPANISH_NI.name(), "Іспанський"},
            {TextType.WRITE_LOGIN.name(), "Введіть логін"},
            {TextType.WRITE_PASSWORD.name(), "Введіть пароль"},
            {TextType.LOGIN_BUTTON.name(), "Входу"},
            {TextType.REGISTER_BUTTON.name(), "Реєстрація"},
            {TextType.BACK_BUTTON.name(), "Назад"},
            {TextType.LOGIN_LABEL.name(), "Логін"},
            {TextType.PASSWORD_LABEL.name(), "Пароль"},
            {TextType.CHOOSE_OBJECT.name(), "Виберіть об'єкт"},
            {TextType.CHOOSE_PATH.name(), "Вкажіть шлях"},
            {TextType.TABLE.name(), "Таблиця"},
            {TextType.PANEL.name(), "Графічне зображення"},
            {TextType.WELCOME_LABEL.name(), "Ласкаво просимо, "},
            {TextType.CHANGER_LABEL.name(), "Редактор"},
            {TextType.DATE_LABEL.name(), "Дата створення:"},
            {TextType.SIZE_LABEL.name(), "Розмір:"},
            {TextType.NAME_LABEL.name(), "Ім'я:"},
            {TextType.CUP_OF_TEA.name(), "Чашка чаю"},
            {TextType.FULLNESS_LABEL.name(), "Заповненість:"},
            {TextType.TEA_TYPE_LABEL.name(), "Тип чаю:"},
            {TextType.ADD_BUTTON.name(), "Додавши"},
            {TextType.CHANGE_BUTTON.name(), "Змінивши"},
            {TextType.REMOVE_BUTTON.name(), "Видалити"},
            {TextType.REMOVE_ALL_BUTTON.name(), "Видалити всі"},
            {TextType.REMOVE_GREATER_BUTTON.name(), "Видалити великі"},
            {TextType.IMPORT_BUTTON.name(), "Імпортувати з файлу"},
            {TextType.CLASS_COLLECTION_LABEL.name(), "У колекції зберігаються об'єкти типу: Alice"},
            {TextType.PATH_LABEL.name(), "Шлях:"},
            {TextType.COLLECTION_LABEL.name(), "Колекція"},
            {TextType.COUNT_LABEL.name(), "Кількість об'єктів в колекції:"},
            {TextType.FILE_NOT_EXIST.name(), "Файл не існує"},
            {TextType.IS_NOT_FILE.name(), "Це не файл"},
            {TextType.CANNOT_READ.name(), "Неможливо вважати файл"},
            {TextType.OWNER_LABEL.name(), "Власник:"},
            {TextType.POLITENESS_LABEL.name(), "Ввічливість:"},
    };

    @Override
    protected Object[][] getContents() {
        return contents;
    }
}
